Repository redBorder/cookbook-memcached, pull requests merged in 2024-04, with the labels that each got.

#6 reduce loglevel output
  resources/templates/default/memcached.erb
Labels: size/XS, kind/bug

#8 Remove log directory as is not needed with systemd, we will use journ…
  resources/attributes/default.rb
  resources/providers/config.rb
  resources/resources/config.rb
  resources/templates/default/memcached.erb
Labels: duplicate, enhancement, size/S, kind/bug

#12 Added ../rpm.yml to .github/workflows/
  .github/workflows/rpm.yml
Labels: kind/feature, size/M
